config/routes.rb
# == Route Map
#
#                    Prefix Verb URI Pattern                                                                              Controller#Action
#                    boards GET  /boards(.:format)                                                                        boards#index
#                 new_board GET  /boards/new(.:format)                                                                    boards#new
#                     board GET  /boards/:id(.:format)                                                                    boards#show
#        rails_service_blob GET  /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET  /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET  /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT  /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users
  resources :boards, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  root 'boards#index'

  get "users/profile/:id", to: "users#profile"

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  body        :text(65535)      not null
#  title       :string(255)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint
#  user_id     :bigint           not null
#
# Indexes
#
#  fk_rails_0732f8ef3d          (user_id)
#  index_boards_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#

class Board < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :category
  belongs_to :user

  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 1000 }
  validates :category_id, presence: true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint
#
# Indexes
#
#  index_categories_on_board_id  (board_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#

class Category < ApplicationRecord
  has_many :boards
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  comment    :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint
#  user_id    :bigint           not null
#
# Indexes
#
#  fk_rails_03de2dc08c         (user_id)
#  index_comments_on_board_id  (board_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#  fk_rails_...  (user_id => users.id)
#

class Comment < ApplicationRecord
  belongs_to :board
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 1000 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  image                  :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  unconfirmed_email      :string(255)
#  user_name              :string(255)      not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :user_name, presence: true, length: { maximum: 8 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :image])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:user_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :image])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :find_board_from_id, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :permit_user!, only: [:edit, :update, :destroy]

  def index
    @boards = params[:category_id].present? ? Category.find(params[:category_id]).boards : Board.all
    @boards = @boards.page(params[:page])
  end

  def new
    @board = Board.new
  end

  def create
    board = Board.new(board_params)
    if board.save
      redirect_to boards_path, flash: {notice: "掲示板「#{board.title}」を作成しました"}
    else
      redirect_back fallback_location: new_board_path, flash: {alert: board.errors.full_messages}
    end
  end

  def show
    @comment = Comment.new(board_id: @board.id)
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to board_path, flash: {notice: "掲示板「#{@board.title}」を編集しました"}
    else
      redirect_back fallback_location: edit_board_path, flash: {alert: @board.errors.full_messages}
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, flash: {notice: "掲示板「#{@board.title}」を削除しました"}
  end


  private
  def board_params
    params.require(:board).permit(:title, :body, :category_id, :user_id)
  end

  def find_board_from_id
    @board = Board.find(params[:id])
  end

  def permit_user!
    if @board.user_id == current_user.id
      return
    else
      redirect_back fallback_location: boards_path, flash: {notice: "自分の投稿のみ編集できます"}
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    comment = Comment.new(comment_params)
    if comment.save
      redirect_to comment.board
    else
      redirect_back fallback_location: comment.board, flash: {alert: comment.errors.full_messages}
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
      if @comment.user_id == current_user.id
        @comment.destroy
        redirect_to board_path(@comment.board_id), flash: {notice: "コメントを削除しました"}
      else
        redirect_back fallback_location: board_path, flash: {notice: "自分のコメントのみ削除できます"}
      end
  end

  private
  def comment_params
    params.require(:comment).permit(:board_id, :comment, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = User.find(params[:id])
    @boards = Board.where(user_id: @user.id).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_board_form.html.erb
<div class="card">

  <div class="card-header">
    <% if current_user && current_user.id == @board.user_id %>
      <%=link_to "削除", board_path, class: "btn btn-outline-danger", method: :delete, data: {confirm: "本当に掲示板を削除しますか？"} %>
      <%=link_to "編集", edit_board_path, class: "btn btn-outline-success" %>
    <% end %>

    <h3><%= @board.title %></h3>
    <h6 class="text-muted">作成日時：<%=@board.created_at.to_s(:datetime_jp)%></h6>
    <span class="badge badge-primary"><%= @board.category.name %></span>

  </div>

  <div class="card-body">
    <p><%= @board.body %></p>
  </div>

  <div class="card-footer text-muted">
    <p>作成者：<%= @board.user.user_name %></p>
    <div class="user-image-show">
      <%= link_to image_tag("#{User.find(@board.user_id).image}"), "/users/profile/#{@board.user_id}"%>
    </div>
  </div>

</div>

app/views/boards/_boards_form.html.erb
<table class="table table-hover boards__table">
  <thead class="thead-light">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>カテゴリー</th>
      <th></th>
      <% if current_user %>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%=board.id%></td>
        <td><%=board.title%></td>
        <td>
          <div class="user-image-index">
            <%= link_to image_tag("#{User.find(board.user_id).image}"), "/users/profile/#{board.user_id}"%>
          </div>
          <div class="board-name-index">
            <%=board.user.user_name%>
          </div>
        </td>
        <td><%=board.created_at.to_s(:datetime_jp)%></td>
        <td>
          <div class="category-image">
            <%= image_tag ("#{board.category.id}") %>
          </div>
          <div class="category-name">
            <%=board.category.name %>
          </div>
        </td>
        <td><%=link_to "詳細", board, class: "btn btn-outline-success" %></td>
        <% if current_user %>
          <td>
            <% if current_user && board.user_id == current_user.id %>
                <%=link_to "編集", edit_board_path(board), class: "btn btn-outline-success" %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @boards %>

app/views/boards/_flash.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <% flash[:alert].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </div>

<% elsif flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/boards/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/boards">Football Forum</a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/boards">HOME</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/boards">ABOUT</a>
      </li>

      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" id="navbarDropdownMenuLink" aria-haspopup="true" aria-expanded="false">メニュー</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <% if current_user == nil %>
            <%= link_to "ログイン", new_user_session_path, method: :get, class: "dropdown-item" %>
            <%= link_to "新規登録", new_user_registration_path, method: :get, class: "dropdown-item"%>
          <% elsif user_signed_in? %>
            <%= link_to "マイページ", "/users/profile/#{current_user.id}", class: "dropdown-item" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%= link_to "ユーザーを編集", edit_user_registration_path, method: :get, class: "dropdown-item" %>
          <% end %>
        </div><!-- ./dropdown-menu -->
      </li>
    </ul>
    <% if current_user %>
      <div class="user-name-header">
        ログイン中：<%= link_to current_user.user_name, "/users/profile/#{current_user.id}" %>
      </div>
      <div class="user-image-header">
        <%= link_to image_tag("#{current_user.image}"), "/users/profile/#{current_user.id}"%>
      </div>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarForm">
    <form class="form-inline my-2 my-lg-0 ml-auto">
      <div class="header_linkbox">
        <% if controller.action_name == "index" %>
          <%= form_with url: boards_path, method: :get, class: "boards__searchForm" do %>
            <%= select_tag :category_id,
                           options_from_collection_for_select(Category.all, :id, :name, params[:category_id]),
                           {
                             prompt: "カテゴリーで絞り込み",
                             class: "form-control boards__select",
                             onchange: "submit(this.form);"
                           }
            %>
          <% end %>
        <% end %>
      </div>
      <div class="header_linkbox">
        <%=link_to "新規作成", new_board_path, class: "btn btn-outline-primary" %>
      </div>
    </form>
  </div>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/boards/_new_and_edit_form.html.erb
<%= form_with model: board, local: true do |f| %>
<%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="form-group">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body, "本文" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <span>カテゴリー</span>
    <%= f.select :category_id, Category.all.map { |category| [category.name, category.id] }, {include_blank: 'カテゴリーを選択してください'}, class:"form-control"  %>
  </div>

  <%= f.submit "投稿", class: "btn btn-success" %>
<% end %>

app/views/boards/_new_board_form.html.erb
<%= form_with model: board, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, "名前" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body, "本文" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <%= f.submit "保存", class: "btn btn-success" %>
<% end %>

app/views/boards/edit.html.erb
<h1>掲示板編集</h1>

<%= render partial: "boards/flash" %>
<%= render partial: "new_and_edit_form", locals: {board: @board} %>

app/views/boards/index.html.erb
<%= render partial: "boards/flash" %>
<%= render partial: "boards/boards_form" %>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <%=link_to "掲示板一覧", boards_path, class: "btn btn-outline-primary" %>
  </div>
</div>
<%= render partial: "boards/flash" %>
<%= render partial: "new_and_edit_form", locals: {board: @board} %>

app/views/boards/show.html.erb
<%= render partial: "boards/flash" %>
<%= render partial: "boards/board_form", locals: {board: @board} %>
<% if current_user %>
<%= render partial: "comments/comment_form", locals: {comment: @comment }%>
<% end %>

<div class="p-comment__list">
  <div class="p-comment__listTitle">コメント</div>
  <%= render @board.comments %>
</div>

app/views/comments/_comment.html.erb
<div class="p-comment__item">
  <p><%= simple_format(comment.comment) %></p>
  <div class="p-comment__bottomLine">
    <span>
      <% if current_user && current_user.id == comment.user_id%>
        <%=link_to "削除", comment_path(comment), class: "btn btn-outline-danger", method: :delete, data: {confirm: "本当に掲示板を削除しますか？"} %>
      <% end %>
    </span>
    <span>ID:<%= comment.id %></span>
    <span><%= comment.user.user_name %></span>
    <span><%= link_to image_tag("#{User.find(comment.user_id).image}"), "/users/profile/#{comment.user_id}"%></span>
    <span><%= comment.created_at.to_s(:datetime_jp) %></span>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<div class="p-comment__formBox">
<p class="p-comment__formTitle">コメント記入</p>
<%= form_with model: comment do |f| %>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :board_id %>

  <div class="form-group">
    <%= f.label :comment, "本文" %>
    <%= f.text_area :comment, class: "form-control" %>
  </div>

  <%= f.submit "投稿", class: "btn btn-success" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "boards/header" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/profile.html.erb
<div class="user">
  <div class="user-image-profile">
    <%= image_tag("#{@user.image}")%>
  </div>
  <div class="user-name-profile">
    <h3><%= @user.user_name %></h3>
  </div>
</div>

</br>

<%= render partial: "boards/flash" %>
<%= render partial: "boards/boards_form" %>